export const slideOrder = [
	'title',
	'outcomes',
	'mismanaged',
	'what-is-rlm',
	'rlms-new-reasoning-models',
	'too-hot-to-benchmark',
	'rlm-not',
	'towards-recursive-coding-agents-trees',
	'towards-recursive-coding-agents',
	'ypi',
	'other-notable-projects',
	'claude-rlm',
	'workflows',
	'openprose',
	'openprose-rlm-examples',
	'applied-examples',
	'takeaways',
	'closing'
] as const;
